name: upgrade_api_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  http: ^0.13.5
  intl: ^0.17.0
  crypto: ^3.0.3   # MD5加密

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
