name: upgradelink_api_dart
version: 1.0.0
description: upgradelink_api_dart.
repository: https://github.com/toolsetlink/upgradelink-api-dart
homepage: https://github.com/toolsetlink/upgradelink-api-dart
issue_tracker: https://github.com/toolsetlink/upgradelink-api-dart

environment:
  sdk: ^3.6.1

dependencies:
  http: ^0.13.5
  intl: ^0.17.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
